#!/usr/bin/env python3

import os
import sys

from saveme.api import CommandLine

sys.path += [ os.path.abspath(os.path.dirname(sys.argv[0])  + "/../lib") ]


cl = CommandLine()
sys.exit(cl.mirroradm(sys.argv))
