#!/usr/bin/env python3

import sys,os
sys.path += [ os.path.abspath(os.path.dirname(sys.argv[0])  + "/../lib") ]

from saveme.api import CommandLine

cl = CommandLine()
sys.exit(cl.mirroradm(sys.argv))
