#!/usr/bin/env python3

import os
import sys

try:
    sys.path += [ os.path.abspath(os.path.dirname(sys.argv[0])  + "/../lib") ]
    from saveme.api import CommandLine
except ImportError:
    pass



cl = CommandLine()
sys.exit(cl.snapmgr(sys.argv))
