name: Build Status

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS Packages
      run: |
        sudo apt-get -y install libsnappy-dev
        sudo apt-get -y install liblz4-dev
        sudo apt-get -y install gcc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade nox setuptools wheel codecov
        pip install -r test-requirements.txt
        pip install -e ".[compression]"
    - name: NOX framework preflight check
      run: |
        nox -s check
    - name: NOX framework test
      run: |
        nox -s test-${{ matrix.python-version }} -- -m "not live" --cov-config=.avoidtestcov
    - name: Upload coverage report
      run: |
        codecov --token=${{ secrets.CODECOV_BUILD_PYSANDRA }}
